# Railway Nixpacks Configuration for eCademy

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "cd web && npm ci && cd .."
]

[phases.build]
cmds = [
    "cd web && npm run build && cd .."
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
