"""
eCademy Configuration Module
"""
from .settings import (
    NETHUNT_STATUS_MAPPING,
    NETHUNT_BASE_URL,
    NETHUNT_AUTH,
    NETHUNT_TIMEOUT,
    NETHUNT_FOLDER_ID,
    ALFACRM_STATUS_MAPPING,
    LOG_LEVEL,
    LOG_FORMAT,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    RETRY_MAX_ATTEMPTS,
    RETRY_EXPONENTIAL_BASE,
    RETRY_MIN_WAIT,
    RETRY_MAX_WAIT
)

__all__ = [
    "NETHUNT_STATUS_MAPPING",
    "NETHUNT_BASE_URL",
    "NETHUNT_AUTH",
    "NETHUNT_TIMEOUT",
    "NETHUNT_FOLDER_ID",
    "ALFACRM_STATUS_MAPPING",
    "LOG_LEVEL",
    "LOG_FORMAT",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "RETRY_MAX_ATTEMPTS",
    "RETRY_EXPONENTIAL_BASE",
    "RETRY_MIN_WAIT",
    "RETRY_MAX_WAIT"
]
